### ISSUE TITLE
Default to Drupal 9

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-container#27]
Currently this container's entrypoint will download or install Drupal 8.x:

```
DRUPAL_CLONE_BRANCH=${DRUPAL_CLONE_BRANCH:-"8.8.x"}
DRUPAL_PROJECT_VERSION=${DRUPAL_PROJECT_VERSION:-"^8@dev"}
```

These defaults should be changed to the Drupal 9 equivalents.

**Comment by dhop90** [comment]
I just built the drupal-container and it installed Drupal 9 instead of 8 on a pidramble cluster.  I'm not able to configure Drupal 9.0.0, I'm getting the following error:

"DATABASE SETTINGS
Resolve all issues below to continue the installation. For help configuring your database server, see the installation handbook, or contact your hosting provider.
The database server version 5.5.60-0+deb7u1 is less than the minimum required version 5.7.8."

 $ k logs -n drupal mysql-8bbdcb879-vbq8m
200604 17:32:08 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
200604 17:32:08 [Note] mysqld (mysqld 5.5.60-0+deb7u1) starting as process 1 ...
200604 17:32:08 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
200604 17:32:08 [Note] Plugin 'FEDERATED' is disabled.
200604 17:32:08 InnoDB: The InnoDB memory heap is disabled
200604 17:32:08 InnoDB: Mutexes and rw_locks use GCC atomic builtins
200604 17:32:08 InnoDB: Compressed tables use zlib 1.2.7
200604 17:32:08 InnoDB: Using Linux native AIO
200604 17:32:08 InnoDB: Initializing buffer pool, size = 128.0M
200604 17:32:08 InnoDB: Completed initialization of buffer pool
200604 17:32:08 InnoDB: highest supported file format is Barracuda.
200604 17:32:08  InnoDB: Waiting for the background threads to start
200604 17:32:09 InnoDB: 5.5.60 started; log sequence number 1595675
200604 17:32:09 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
200604 17:32:09 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
200604 17:32:09 [Note] Server socket created on IP: '0.0.0.0'.
200604 17:32:12 [Note] Event Scheduler: Loaded 0 events
200604 17:32:12 [Note] mysqld: ready for connections.
Version: '5.5.60-0+deb7u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Debian)

How do I build drupal-container using Drupal 8?

Thanks,
Dave

**Comment by dhop90** [comment]
I was able to get drupal 8.9.0 install by building drupal-container and setting 

DRUPAL_DOWNLOAD_METHOD=${DRUPAL_DOWNLOAD_METHOD:-tarball}
DRUPAL_DOWNLOAD_URL="https://ftp.drupal.org/files/projects/drupal-8.9.0.tar.gz"

in docker-entrypoint.sh

**Comment by geerlingguy** [comment]
@dhop90 - Yeah, sorry about that—I think you're also running into https://github.com/geerlingguy/drupal-pi/issues/45 — I've just pushed some fixes to the `drupal-pi` codebase (`master` branch) that should use a better version of the MySQL database image that's compatible with Drupal 9 ;-)

**Comment by ayanny** [comment]
My R-Pi's are ARMv7 Processor rev 3 (v7l). I am running into the same error above, is there an sql docker image for this Pi Architecture?

Thanks

**Comment by geerlingguy** [comment]
This is fixed, but please open separate issues for any other things you may run into.
